apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-deployment
spec:
  selector:
    matchLabels:
      app: todo-backend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: wizelineacademy/todo-backend
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_PORT_27017_TCP_PORT
          value: "27017"
        - name: MONGODB_PORT_27017_TCP_ADDR
          value: database ## service name

---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  type:
  selector:
  ports:
    - protocol:
      targetPort:
      port:
      nodePort:
