apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment
spec:
  selector:
    matchLabels:
      app: todo-frontend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
      - name: todo-frontend
        image: wizelineacademy/todo-frontend:devmode
        ports:
        - containerPort: 9090
        env:
            - name: API_URL
              value: ### Need BACKEND public ENDPINT 

---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
spec:
  type: NodePort
  selector:
  ports:
    - protocol:
      targetPort:
      port:
      nodePort:
